"""Stable error codes for the Browser Capability."""

PERMISSION_DENIED = "permission_denied"
UNSUPPORTED_OPERATION = "unsupported_operation"
INVALID_URL = "invalid_url"
INVALID_QUERY = "invalid_query"
INVALID_DESTINATION = "invalid_destination"
INVALID_TIMEOUT = "invalid_timeout"
NETWORK_UNAVAILABLE = "network_unavailable"
DOWNLOAD_FAILED = "download_failed"
TIMEOUT = "timeout"
UNSUPPORTED_CONTENT = "unsupported_content"
DESTINATION_EXISTS = "destination_exists"
DOWNLOAD_TOO_LARGE = "download_too_large"
CANCELLED = "cancelled"
