"""Memovi Capability Framework.

Provider-agnostic capability abstractions for discovery, permission metadata,
safe single-invocation execution, the Capability Execution Engine, and the
Capability Planner (plan/validate only — never executes capabilities).
"""

from memovi_automation.application import (
    Capability,
    CapabilityExecutionEngine,
    CapabilityInvoker,
    CapabilityPlanner,
    CapabilityRegistry,
    ExecutionAuditStore,
    ExecutionPlanValidator,
    PermissionPolicyStore,
    PlanExecutionService,
)
from memovi_automation.browser import (
    CAPABILITY_ID as BROWSER_CAPABILITY_ID,
)
from memovi_automation.browser import (
    BrowserCapability,
    BrowserCapabilityConfig,
    register_browser_capability,
)
from memovi_automation.domain import (
    BROWSER_DOWNLOAD,
    BROWSER_READ,
    BROWSER_SEARCH,
    CLIPBOARD_READ,
    CLIPBOARD_WRITE,
    DEFAULT_EXECUTION_POLICY,
    FILESYSTEM_CREATE,
    FILESYSTEM_DELETE,
    FILESYSTEM_MODIFY,
    FILESYSTEM_MOVE,
    FILESYSTEM_READ,
    FILESYSTEM_WRITE,
    GIT_NETWORK,
    GIT_READ,
    GIT_WRITE,
    NOTIFICATIONS_SEND,
    TERMINAL_EXECUTE,
    AutomationDomainError,
    CancellationToken,
    CapabilityCancelledError,
    CapabilityContext,
    CapabilityError,
    CapabilityExecutionContext,
    CapabilityExecutionError,
    CapabilityExecutionNotFoundError,
    CapabilityExecutionPolicy,
    CapabilityExecutionRequest,
    CapabilityExecutionResult,
    CapabilityExecutionStatus,
    CapabilityMetadata,
    CapabilityParameter,
    CapabilityPermission,
    CapabilityRequest,
    CapabilityResult,
    CapabilityTimeoutError,
    ExecutionAuditEntry,
    ExecutionDependency,
    ExecutionPlan,
    ExecutionPlanResult,
    ExecutionStep,
    ExecutionStepResult,
    InvalidCapabilityArgumentsError,
    InvalidCapabilityError,
    InvalidExecutionPlanError,
    PermissionMode,
    UnknownCapabilityError,
    redact_arguments,
)
from memovi_automation.filesystem import (
    CAPABILITY_ID as FILESYSTEM_CAPABILITY_ID,
)
from memovi_automation.filesystem import (
    FilesystemCapability,
    FilesystemCapabilityConfig,
    register_filesystem_capability,
)
from memovi_automation.infrastructure import (
    InMemoryExecutionAuditStore,
    InMemoryPermissionPolicyStore,
)
from memovi_automation.git import (
    CAPABILITY_ID as GIT_CAPABILITY_ID,
)
from memovi_automation.git import (
    GitCapability,
    GitCapabilityConfig,
    register_git_capability,
)
from memovi_automation.terminal import (
    CAPABILITY_ID as TERMINAL_CAPABILITY_ID,
)
from memovi_automation.terminal import (
    TerminalCapability,
    TerminalCapabilityConfig,
    register_terminal_capability,
)

__all__ = [
    "BROWSER_CAPABILITY_ID",
    "BROWSER_DOWNLOAD",
    "BROWSER_READ",
    "BROWSER_SEARCH",
    "CLIPBOARD_READ",
    "CLIPBOARD_WRITE",
    "DEFAULT_EXECUTION_POLICY",
    "FILESYSTEM_CAPABILITY_ID",
    "FILESYSTEM_CREATE",
    "FILESYSTEM_DELETE",
    "FILESYSTEM_MODIFY",
    "FILESYSTEM_MOVE",
    "FILESYSTEM_READ",
    "FILESYSTEM_WRITE",
    "GIT_CAPABILITY_ID",
    "GIT_NETWORK",
    "GIT_READ",
    "GIT_WRITE",
    "NOTIFICATIONS_SEND",
    "TERMINAL_CAPABILITY_ID",
    "TERMINAL_EXECUTE",
    "AutomationDomainError",
    "BrowserCapability",
    "BrowserCapabilityConfig",
    "CancellationToken",
    "Capability",
    "CapabilityCancelledError",
    "CapabilityContext",
    "CapabilityError",
    "CapabilityExecutionContext",
    "CapabilityExecutionEngine",
    "CapabilityExecutionError",
    "CapabilityExecutionNotFoundError",
    "CapabilityExecutionPolicy",
    "CapabilityExecutionRequest",
    "CapabilityExecutionResult",
    "CapabilityExecutionStatus",
    "CapabilityInvoker",
    "CapabilityMetadata",
    "CapabilityParameter",
    "CapabilityPermission",
    "CapabilityPlanner",
    "CapabilityRegistry",
    "CapabilityRequest",
    "CapabilityResult",
    "CapabilityTimeoutError",
    "ExecutionAuditEntry",
    "ExecutionAuditStore",
    "ExecutionDependency",
    "ExecutionPlan",
    "ExecutionPlanResult",
    "ExecutionPlanValidator",
    "ExecutionStep",
    "ExecutionStepResult",
    "FilesystemCapability",
    "FilesystemCapabilityConfig",
    "GitCapability",
    "GitCapabilityConfig",
    "InMemoryExecutionAuditStore",
    "InMemoryPermissionPolicyStore",
    "InvalidCapabilityArgumentsError",
    "InvalidCapabilityError",
    "InvalidExecutionPlanError",
    "PermissionMode",
    "PermissionPolicyStore",
    "PlanExecutionService",
    "TerminalCapability",
    "TerminalCapabilityConfig",
    "UnknownCapabilityError",
    "redact_arguments",
    "register_browser_capability",
    "register_filesystem_capability",
    "register_git_capability",
    "register_terminal_capability",
]
