"""Memovi Capability Framework.

Provider-agnostic capability abstractions for discovery, permission metadata,
and safe single-invocation execution. Not an agent framework.
"""

from memovi_automation.application import Capability, CapabilityInvoker, CapabilityRegistry
from memovi_automation.domain import (
    BROWSER_READ,
    CLIPBOARD_READ,
    CLIPBOARD_WRITE,
    DEFAULT_EXECUTION_POLICY,
    FILESYSTEM_READ,
    FILESYSTEM_WRITE,
    GIT_READ,
    GIT_WRITE,
    NOTIFICATIONS_SEND,
    TERMINAL_EXECUTE,
    AutomationDomainError,
    CancellationToken,
    CapabilityCancelledError,
    CapabilityContext,
    CapabilityError,
    CapabilityExecutionError,
    CapabilityExecutionPolicy,
    CapabilityMetadata,
    CapabilityParameter,
    CapabilityPermission,
    CapabilityRequest,
    CapabilityResult,
    CapabilityTimeoutError,
    InvalidCapabilityArgumentsError,
    InvalidCapabilityError,
    UnknownCapabilityError,
)
from memovi_automation.filesystem import (
    CAPABILITY_ID as FILESYSTEM_CAPABILITY_ID,
    FilesystemCapability,
    FilesystemCapabilityConfig,
    register_filesystem_capability,
)

__all__ = [
    "BROWSER_READ",
    "CLIPBOARD_READ",
    "CLIPBOARD_WRITE",
    "DEFAULT_EXECUTION_POLICY",
    "FILESYSTEM_CAPABILITY_ID",
    "FILESYSTEM_READ",
    "FILESYSTEM_WRITE",
    "GIT_READ",
    "GIT_WRITE",
    "NOTIFICATIONS_SEND",
    "TERMINAL_EXECUTE",
    "AutomationDomainError",
    "CancellationToken",
    "Capability",
    "CapabilityCancelledError",
    "CapabilityContext",
    "CapabilityError",
    "CapabilityExecutionError",
    "CapabilityExecutionPolicy",
    "CapabilityInvoker",
    "CapabilityMetadata",
    "CapabilityParameter",
    "CapabilityPermission",
    "CapabilityRegistry",
    "CapabilityRequest",
    "CapabilityResult",
    "CapabilityTimeoutError",
    "FilesystemCapability",
    "FilesystemCapabilityConfig",
    "InvalidCapabilityArgumentsError",
    "InvalidCapabilityError",
    "UnknownCapabilityError",
    "register_filesystem_capability",
]
