"""Memovi Capability Framework.

Provider-agnostic capability abstractions for discovery, permission metadata,
safe single-invocation execution, and the Capability Execution Engine.
"""

from memovi_automation.application import (
    Capability,
    CapabilityExecutionEngine,
    CapabilityInvoker,
    CapabilityRegistry,
    ExecutionAuditStore,
    PermissionPolicyStore,
)
from memovi_automation.domain import (
    BROWSER_READ,
    CLIPBOARD_READ,
    CLIPBOARD_WRITE,
    DEFAULT_EXECUTION_POLICY,
    FILESYSTEM_READ,
    FILESYSTEM_WRITE,
    GIT_READ,
    GIT_WRITE,
    NOTIFICATIONS_SEND,
    TERMINAL_EXECUTE,
    AutomationDomainError,
    CancellationToken,
    CapabilityCancelledError,
    CapabilityContext,
    CapabilityError,
    CapabilityExecutionContext,
    CapabilityExecutionError,
    CapabilityExecutionNotFoundError,
    CapabilityExecutionPolicy,
    CapabilityExecutionRequest,
    CapabilityExecutionResult,
    CapabilityExecutionStatus,
    CapabilityMetadata,
    CapabilityParameter,
    CapabilityPermission,
    CapabilityRequest,
    CapabilityResult,
    CapabilityTimeoutError,
    ExecutionAuditEntry,
    InvalidCapabilityArgumentsError,
    InvalidCapabilityError,
    PermissionMode,
    UnknownCapabilityError,
    redact_arguments,
)
from memovi_automation.filesystem import (
    CAPABILITY_ID as FILESYSTEM_CAPABILITY_ID,
)
from memovi_automation.filesystem import (
    FilesystemCapability,
    FilesystemCapabilityConfig,
    register_filesystem_capability,
)
from memovi_automation.infrastructure import (
    InMemoryExecutionAuditStore,
    InMemoryPermissionPolicyStore,
)

__all__ = [
    "BROWSER_READ",
    "CLIPBOARD_READ",
    "CLIPBOARD_WRITE",
    "DEFAULT_EXECUTION_POLICY",
    "FILESYSTEM_CAPABILITY_ID",
    "FILESYSTEM_READ",
    "FILESYSTEM_WRITE",
    "GIT_READ",
    "GIT_WRITE",
    "NOTIFICATIONS_SEND",
    "TERMINAL_EXECUTE",
    "AutomationDomainError",
    "CancellationToken",
    "Capability",
    "CapabilityCancelledError",
    "CapabilityContext",
    "CapabilityError",
    "CapabilityExecutionContext",
    "CapabilityExecutionEngine",
    "CapabilityExecutionError",
    "CapabilityExecutionNotFoundError",
    "CapabilityExecutionPolicy",
    "CapabilityExecutionRequest",
    "CapabilityExecutionResult",
    "CapabilityExecutionStatus",
    "CapabilityInvoker",
    "CapabilityMetadata",
    "CapabilityParameter",
    "CapabilityPermission",
    "CapabilityRegistry",
    "CapabilityRequest",
    "CapabilityResult",
    "CapabilityTimeoutError",
    "ExecutionAuditEntry",
    "ExecutionAuditStore",
    "FilesystemCapability",
    "FilesystemCapabilityConfig",
    "InMemoryExecutionAuditStore",
    "InMemoryPermissionPolicyStore",
    "InvalidCapabilityArgumentsError",
    "InvalidCapabilityError",
    "PermissionMode",
    "PermissionPolicyStore",
    "UnknownCapabilityError",
    "redact_arguments",
    "register_filesystem_capability",
]
