"""Production Filesystem Capability — reference capability implementation."""

from memovi_automation.filesystem.capability import (
    CAPABILITY_ID,
    READ_OPERATIONS,
    WRITE_OPERATIONS,
    FilesystemCapability,
    register_filesystem_capability,
)
from memovi_automation.filesystem.config import FilesystemCapabilityConfig
from memovi_automation.filesystem.errors import (
    ALREADY_EXISTS,
    DESTINATION_REQUIRED,
    DIRECTORY_NOT_EMPTY,
    FILE_NOT_FOUND,
    FILE_TOO_LARGE,
    INVALID_PATH,
    NOT_A_DIRECTORY,
    NOT_A_FILE,
    NOT_TEXT_FILE,
    OVERWRITE_CONFIRMATION_REQUIRED,
    OVERWRITE_REJECTED,
    PERMISSION_DENIED,
    SAME_PATH,
    TRASH_UNAVAILABLE,
    UNSAFE_TARGET,
    UNSUPPORTED_OPERATION,
    WRITE_TOO_LARGE,
)

__all__ = [
    "ALREADY_EXISTS",
    "CAPABILITY_ID",
    "DESTINATION_REQUIRED",
    "DIRECTORY_NOT_EMPTY",
    "FILE_NOT_FOUND",
    "FILE_TOO_LARGE",
    "INVALID_PATH",
    "NOT_A_DIRECTORY",
    "NOT_A_FILE",
    "NOT_TEXT_FILE",
    "OVERWRITE_CONFIRMATION_REQUIRED",
    "OVERWRITE_REJECTED",
    "PERMISSION_DENIED",
    "READ_OPERATIONS",
    "SAME_PATH",
    "TRASH_UNAVAILABLE",
    "UNSAFE_TARGET",
    "UNSUPPORTED_OPERATION",
    "WRITE_OPERATIONS",
    "WRITE_TOO_LARGE",
    "FilesystemCapability",
    "FilesystemCapabilityConfig",
    "register_filesystem_capability",
]
