"""Stable error codes for the Filesystem Capability."""

PERMISSION_DENIED = "permission_denied"
FILE_NOT_FOUND = "file_not_found"
INVALID_PATH = "invalid_path"
UNSUPPORTED_OPERATION = "unsupported_operation"
NOT_A_FILE = "not_a_file"
NOT_A_DIRECTORY = "not_a_directory"
NOT_TEXT_FILE = "not_text_file"
FILE_TOO_LARGE = "file_too_large"
ALREADY_EXISTS = "already_exists"
OVERWRITE_REJECTED = "overwrite_rejected"
OVERWRITE_CONFIRMATION_REQUIRED = "overwrite_confirmation_required"
DIRECTORY_NOT_EMPTY = "directory_not_empty"
TRASH_UNAVAILABLE = "trash_unavailable"
WRITE_TOO_LARGE = "write_too_large"
DESTINATION_REQUIRED = "destination_required"
SAME_PATH = "same_path"
UNSAFE_TARGET = "unsafe_target"
