"""Memovi Model Provider Framework.

Provider-neutral model abstractions for discovery, configuration, health,
capability inspection, and completion. Not a marketplace or UI layer.
"""

from memovi_models.application import ModelProvider, ModelRegistry
from memovi_models.domain import (
    AUTHENTICATION_ERROR,
    INVALID_CONFIGURATION_ERROR,
    INVALID_REQUEST_ERROR,
    PROVIDER_ANTHROPIC,
    PROVIDER_ERROR,
    PROVIDER_FAKE,
    PROVIDER_GEMINI,
    PROVIDER_LM_STUDIO,
    PROVIDER_OLLAMA,
    PROVIDER_OPENAI,
    PROVIDER_OPENROUTER,
    RATE_LIMIT_ERROR,
    TIMEOUT_ERROR,
    UNAVAILABLE_ERROR,
    UNSUPPORTED_CAPABILITY_ERROR,
    InvalidModelError,
    ModelCapabilities,
    ModelError,
    ModelMessage,
    ModelMetadata,
    ModelProviderError,
    ModelRequest,
    ModelResponse,
    ModelUsage,
    ModelsDomainError,
    ProviderConfiguration,
    ProviderHealth,
    UnknownModelError,
    UnknownProviderError,
)
from memovi_models.infrastructure import FakeModelProvider

__all__ = [
    "AUTHENTICATION_ERROR",
    "INVALID_CONFIGURATION_ERROR",
    "INVALID_REQUEST_ERROR",
    "PROVIDER_ANTHROPIC",
    "PROVIDER_ERROR",
    "PROVIDER_FAKE",
    "PROVIDER_GEMINI",
    "PROVIDER_LM_STUDIO",
    "PROVIDER_OLLAMA",
    "PROVIDER_OPENAI",
    "PROVIDER_OPENROUTER",
    "RATE_LIMIT_ERROR",
    "TIMEOUT_ERROR",
    "UNAVAILABLE_ERROR",
    "UNSUPPORTED_CAPABILITY_ERROR",
    "FakeModelProvider",
    "InvalidModelError",
    "ModelCapabilities",
    "ModelError",
    "ModelMessage",
    "ModelMetadata",
    "ModelProvider",
    "ModelProviderError",
    "ModelRegistry",
    "ModelRequest",
    "ModelResponse",
    "ModelUsage",
    "ModelsDomainError",
    "ProviderConfiguration",
    "ProviderHealth",
    "UnknownModelError",
    "UnknownProviderError",
]
