"""Memovi Connector Framework.

Provider-neutral connector abstractions for registration, configuration,
authentication references, synchronization, normalization into Documents,
health, and a scheduler foundation. Includes the production Filesystem
Connector for local folder import and sync.
"""

from memovi_connectors.application import (
    AddFilesystemFolderCommand,
    Connector,
    ConnectorRegistry,
    ConnectorScheduler,
    ConnectorScheduleSpec,
    DocumentImportPort,
    FilesystemFolderService,
    SyncFilesystemFolderCommand,
)
from memovi_connectors.domain import (
    CONNECTOR_CLOUD_STORAGE,
    CONNECTOR_FAKE,
    CONNECTOR_FILESYSTEM,
    CONNECTOR_GITHUB,
    CONNECTOR_GMAIL,
    CONNECTOR_GOOGLE_DRIVE,
    CONNECTOR_NOTION,
    CONNECTOR_OBSIDIAN,
    CONNECTOR_SLACK,
    AuthCredentialRef,
    ConnectorConfiguration,
    ConnectorExecutionContext,
    ConnectorHealth,
    ConnectorMetadata,
    ConnectorResult,
    ConnectorsDomainError,
    ConnectorSyncError,
    InvalidConnectorError,
    NormalizedImportItem,
    NormalizedSourceMetadata,
    UnknownConnectorError,
)
from memovi_connectors.domain.entities import FilesystemFolderConnection
from memovi_connectors.infrastructure import (
    FakeConnector,
    FilesystemConnector,
    InMemoryDocumentImportPort,
    InMemoryFilesystemFolderRepository,
    SqlAlchemyFilesystemFolderRepository,
    register_fake_connector,
    register_filesystem_connector,
)

__all__ = [
    "CONNECTOR_CLOUD_STORAGE",
    "CONNECTOR_FAKE",
    "CONNECTOR_FILESYSTEM",
    "CONNECTOR_GITHUB",
    "CONNECTOR_GMAIL",
    "CONNECTOR_GOOGLE_DRIVE",
    "CONNECTOR_NOTION",
    "CONNECTOR_OBSIDIAN",
    "CONNECTOR_SLACK",
    "AddFilesystemFolderCommand",
    "AuthCredentialRef",
    "Connector",
    "ConnectorConfiguration",
    "ConnectorExecutionContext",
    "ConnectorHealth",
    "ConnectorMetadata",
    "ConnectorRegistry",
    "ConnectorResult",
    "ConnectorScheduleSpec",
    "ConnectorScheduler",
    "ConnectorSyncError",
    "ConnectorsDomainError",
    "DocumentImportPort",
    "FakeConnector",
    "FilesystemConnector",
    "FilesystemFolderConnection",
    "FilesystemFolderService",
    "InMemoryDocumentImportPort",
    "InMemoryFilesystemFolderRepository",
    "InvalidConnectorError",
    "NormalizedImportItem",
    "NormalizedSourceMetadata",
    "SqlAlchemyFilesystemFolderRepository",
    "SyncFilesystemFolderCommand",
    "UnknownConnectorError",
    "register_fake_connector",
    "register_filesystem_connector",
]
