"""Stable error codes for the Git Capability."""

PERMISSION_DENIED = "permission_denied"
UNSUPPORTED_OPERATION = "unsupported_operation"
INVALID_REPOSITORY = "invalid_repository"
NOT_A_GIT_REPOSITORY = "not_a_git_repository"
REPOSITORY_NOT_FOUND = "repository_not_found"
EMPTY_MESSAGE = "empty_message"
INVALID_REF = "invalid_ref"
INVALID_PATHS = "invalid_paths"
INVALID_TIMEOUT = "invalid_timeout"
GIT_FAILED = "git_failed"
MERGE_CONFLICT = "merge_conflict"
AUTHENTICATION_FAILURE = "authentication_failure"
DETACHED_HEAD = "detached_head"
PUSH_REJECTED = "push_rejected"
TIMEOUT = "timeout"
GIT_NOT_AVAILABLE = "git_not_available"
